---
- name: Creates directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0755'
    force: false
  with_items:
    - "{{ app_home_dir }}"
    - "{{ jenkins_home }}"
    - "{{ jenkins_home }}/casc_configs"
    - "{{ jenkins_data }}"

- name: Creates directory for Flyway
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0644'
    force: false
  with_items:
    - "{{ flyway_data }}"
    - "{{ flyway_data_kos }}"
  when: use_flyway

- name: Creates argocd directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0755'
    force: false
  with_items:
    - "{{ jenkins_home }}/argocd/"
  when: use_argocd

- name: Touch argocd config
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: '0600'
  with_items:
    - "{{ jenkins_home }}/argocd/config"
  when: use_argocd

- name: Touch kubeconfig
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: '0600'
  with_items:
    - "{{ jenkins_home }}/kubeconfig"
  when: use_kubeconfig

- name: Creates ssh directory
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0755'
    force: false
  with_items:
    - "{{ jenkins_home }}/.ssh/"
  when: use_ssh

- name: Touch .ssh files
  ansible.builtin.file:
    path: "{{ item }}"
    state: touch
    mode: '0600'
  with_items:
    - "{{ jenkins_home }}/.ssh/id_rsa"
    - "{{ jenkins_home }}/.ssh/id_rsa.pub"
  when: use_ssh

- name: Copy file
  ansible.builtin.template:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    owner: "{{ adm_user }}"
    group: "{{ adm_group }}"
    mode: '0644'
    backup: true
  with_items:
    - { src: '.env.j2', dest: '{{ jenkins_home }}/.env' }
    - { src: 'docker-compose.yml.j2', dest: '{{ jenkins_home }}/docker-compose.yml' }
    - { src: 'gitconfig.j2', dest: '{{ jenkins_home }}/gitconfig' }
    - { src: 'settings.xml.j2', dest: '{{ jenkins_home }}/settings.xml' }

- name: Install Docker SDK for Python
  ansible.builtin.pip:
    name: docker
    state: present
  when: ansible_pkg_mgr != "pacman"
  ignore_errors: true

- name: Log into docker server
  community.docker.docker_login:
    # registry_url: "{{ image_registry_server }}"
    username: "{{ dkr_username }}"
    password: "{{ dkr_passwd }}"
    reauthorize: true
  when: docker_type != 'ghcr.io'

- name: Login to docker [ghcr.io]
  ansible.builtin.shell: echo {{ dkr_passwd }} | docker login ghcr.io -u {{ dkr_username }} --password-stdin
  when: docker_type == 'ghcr.io'

- name: Pull jenkins image from {{ image_registry_server }}
  community.docker.docker_image:
    name: "{{ image_registry_server }}/{{ jenkins_image }}:{{ jenkins_ver }}"
    source: pull
    pull:
      platform: amd64
  when: image_registry_server2

- name: Tag jenkins image
  community.docker.docker_image:
    name: "{{ image_registry_server }}/{{ jenkins_image }}:{{ jenkins_ver }}"
    repository: "{{ image_registry_server2 }}/{{ jenkins_image }}:{{ jenkins_ver }}"
    push: "{{ push_image }}"
    source: local
  when: image_registry_server2

- name: Restart jenkins
  shell: echo success
  notify:
    Restart jenkins
