---
- name: Start jenkins
  community.docker.docker_compose:
    project_src: "{{ jenkins_home }}"
    files:
      - docker-compose.yml
    state: present
  register: result
  changed_when: result.changed
  ignore_errors: true

- name: Start jenkins (using shell command)
  ansible.builtin.shell: "docker-compose -f {{ jenkins_home }}/docker-compose.yml up -d"
  args:
    chdir: "{{ jenkins_home }}"
  when: result is failed
  register: shell_result
  changed_when: shell_result.rc == 0

- name: Stop jenkins
  community.docker.docker_compose:
    project_src: "{{ jenkins_home }}"
    files:
      - docker-compose.yml
    state: absent
  register: result
  changed_when: result.changed
  ignore_errors: true

- name: Stop jenkins (using shell command)
  ansible.builtin.shell: "docker-compose -f {{ jenkins_home }}/docker-compose.yml down"
  args:
    chdir: "{{ jenkins_home }}"
  when: result is failed
  register: shell_result
  changed_when: shell_result.rc == 0

- name: Restart jenkins
  community.docker.docker_compose:
    project_src: "{{ jenkins_home }}"
    files:
      - docker-compose.yml
    state: present
    restarted: yes
  register: result
  changed_when: result.changed
  ignore_errors: true

- name: Restart jenkins (using shell command)
  ansible.builtin.shell: "docker-compose -f {{ jenkins_home }}/docker-compose.yml up -d --force-recreate"
  args:
    chdir: "{{ jenkins_home }}"
  when: result is failed
  register: shell_result
  changed_when: shell_result.rc == 0
